### ISSUE TITLE
Chef Extension Fails frequently with the following error

### ISSUE THREAD

**Issue by aarsan** [chef-partners/azure-chef-extension#114] opened 2016-03-18 20:32 UTC
{ "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "VMExtensionHandlerNonTransientError", "message": "Handler 'Chef.Bootstrap.WindowsAzure.ChefClient' has reported failure for VM Extension 'chefExtension' with terminal error code '1007' and error message: 'Install failed for plugin (name: Chef.Bootstrap.WindowsAzure.ChefClient, version 1210.12.101.1000) with exception Command C:\\Packages\\Plugins\\Chef.Bootstrap.WindowsAzure.ChefClient\\1210.12.101.1000\\install.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has exited with Exit code: 1'" } ] } }

**Comment by Aliasgar16** [comment] 2016-03-21 15:19
Hi @aarsan 

I tried reproducing the issue which you faced for Chef extension version 1210.12.101.1000 version on Windows platform, but unfortunately I could not reproduce the issue as Windows Chef extension got installed and enabled successfully. I tried this process through `azure-powershell` commands and `knife-azure` (with bootstrap protocol as `cloud-api`) plugin.

Can you provide me with more details like which tool you used for this operation, commands used, inputs provided, etc. This will help to locate the root cause with faster pace.

Thanks

**Comment by NimishaS** [comment] 2016-03-30 09:12
@aarsan , any updates on this issue?

**Comment by aarsan** [comment] 2016-04-01 14:12
The issue is sporadic. I face this issue when provisioning a VM with ARM - none of the tools you mentioned. I am provisioning machines all day and about 1/5 fail with that error.

**Comment by NimishaS** [comment] 2016-10-20 07:13
@aarsan , @russellseymour had a discussion with you and I think this issue is resolved now. If so please close this.

**Comment by NimishaS** [comment] 2016-10-20 12:37
Thanks for update @aarsan

**Closed by NimishaS** 2016-10-20 12:37 UTC
