### ISSUE TITLE
% inside encrypted_data_bag_secret disappears

### ISSUE THREAD

**Issue by leevipietilainen** [chef-partners/azure-chef-extension#176] opened 2016-11-15 10:40 UTC
If the secret file contains % character, it disappears during the azure-chef-installation or run phase.

For example on my deploy machine the encrypted_data_bag_secret contains "abc:%123". After deploying with knife azure server create cloud-api, the encrypted_data_bag_secret contents on the destination server is "abc:123".

So far I have troubleshoot it that the "0.settings" files's protected settings does containt the % sign, but somewhere after decryption and placing the C:\chef\encrypted_data_bag_secret file the % sign gets lost.

Tested with commit 51321617ac1b69c009365c535b3d48f55d0ecb6d from master.

**Comment by piyushawasthi** [comment] 2017-02-22 09:26
@leevipietilainen, this issue is not related to `azure-chef-extension`. I have tried creating knife-azure server without using `cloud-api` bootstrap protocol, but still faced the same problem. After debugging found that correct value gets passed to the Azure API. Seems like the issue is in Azure API itself.

**Comment by Vasu1105** [comment] 2019-02-05 10:51
Closing this due to age.

**Closed by Vasu1105** 2019-02-05 10:51 UTC
