### ISSUE TITLE
CommandExecution_1 failure

### ISSUE THREAD

**Issue by amarkulis** [chef-partners/azure-chef-extension#225] opened 2017-08-23 18:14 UTC
We randomly received a CommandExecution_1 failure.  I re ran the command by hand and it completed successfully.  Can we open a new powershell window to run this command?  Or maybe throw in a retry?

8/23/2017 11:35:25] Installed Azure-Chef-Extension gem successfully
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005>set path=C:\opscode\chef\bin;C:\opscode\chef\embedded\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\; 
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005>ruby C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005\bin\chef-enable.rb 
2017-08-23 11:35:29 +0000 extension_root --> C:/Packages/Plugins/Chef.Bootstrap.WindowsAzure.ChefClient/1210.12.109.1005
2017-08-23 11:35:29 +0000 Creating EnableChef object with []...
2017-08-23 11:35:29 +0000 Running Chef extension enable command...
Bootstrap directory [C:/chef] already exists, skipping creation...
2017-08-23 11:35:29 +0000 Creating chef configuration files
[2017-08-23T11:35:30+00:00] ERROR: Expected process to exit with [0], but received '1'
---- Begin output of powershell.exe -nologo -noprofile -executionpolicy "unrestricted" -file C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/azure-chef-extension-0.0.1/lib/chef/azure\helpers\powershell\decrypt_content_on_windows.ps1 D70EF05981D56EDA274293ED7F1ECBFAFB385D41 MIIIbAYJKoZIhvcNAQcDoIIIXTCCCFkCAQAxggFpMIIBZQIBADBNMDkxNzA1BgoJkiaJk/IsZAEZFidXaW5kb3...

**Comment by NimishaS** [comment] 2017-08-29 09:38
@amarkulis , can you please share steps to reproduce this issue? Please share the following details as well:
1. Are you using ARM template for extension? If yes, then plz share the template.
2. In case you are using any azure CLI command, please share that.
3. Are you observing this issue with a particular windows image or with all images?
4. Please share the complete logs from `C:\WindowsAzure\Logs\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005`

**Comment by amarkulis** [comment] 2017-08-29 16:58
We use ARM

"resources": [
    {
      "properties": {
        "publisher": "Chef.Bootstrap.WindowsAzure",
        "type": "ChefClient",
        "typeHandlerVersion": "1210.1",
        "autoUpgradeMinorVersion": false,
        "settings": {
          "bootstrap_options": {
            "environment": "Prod01-T015",
            "chef_server_url": "https://chef2.r1.kcura.com/organizations/brownstein-prod",
            "validation_client_name": "brownstein-prod-validator"
          },
          "client_rb": "# Define path variables\ncurrent_dir = File.dirname(__FILE__)\nif RUBY_PLATFORM =~ /ming(.*)/ then\n  root = \"c:/chef/\"\nelse\n  root = \"/etc/chef/\"\nend\n\n# Chef Info\nssl_verify_mode :verify_none\nclient_key \"#{root}client.pem\"\nnode_name \"Prod01-#{Socket.gethostname}\"\ndisable_event_logger  \"true\"\n\n\n# Sets why_run value\nchef_server_url  \"https://chef2.r1.kcura.com/organizations/brownstein-prod\"\nif File.exist?(client_key)\n  w = Chef::ServerAPI.new(chef_server_url, client_name: node_name, signing_key_filename: client_key, validate_utf8: false)\n  e = w.get(\"/environments/Prod01-T015\")\n  wr_value = e[\"override_attributes\"][\"kcura\"][\"why_run\"]\n  Chef::Config[:why_run] = wr_value\nelse\n  Chef::Config[:why_run] = false\nend\ndata_collector.server_url = nil\n",
          "bootstrap_version": "12.18.31",
          "runlist": "recipe[role-web]"
        },
        "provisioningState": "Failed"
      },
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "location": "centralus",
      "tags": {
        "informationClassification": "Customer Confidential"
      },
      "id": "/subscriptions/80087f18-86ed-454e-8c27-18bde461ffa4/resourceGroups/RG-CentralUS-Prod01-Tenant-015-Web/providers/Microsoft.Compute/virtualMachines/VM-T015WEB001/extensions/ChefExtension",
      "name": "ChefExtension"
    },

This is how the error looks
    }
  ],
  "extensions": [
    {
      "name": "ChefExtension",
      "type": "Chef.Bootstrap.WindowsAzure.ChefClient",
      "typeHandlerVersion": "1210.12.109.1005",
      "statuses": [
        {
          "code": "ProvisioningState/transitioning",
          "level": "Info",
          "displayStatus": "Transitioning",
          "message": "Update failed for plugin (name: Chef.Bootstrap.WindowsAzure.ChefClient, version 1210.12.109.1005) with exception Command C:\\Packages\\Plugins\\Chef.Bootstrap.WindowsAzure.ChefClient\\1210.12.109.1005\\update.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has not exited on time! Killing it..."
        }
      ]
    },
    {

**Comment by NimishaS** [comment] 2017-08-30 13:49
@amarkulis , it's still not clear to me how to reproduce this error. I used `New-AzureRmResourceGroupDeployment` command to create a VM with extension and it worked successfully for me. 
The logs shared by you show error while executing `update.cmd` command. However `update.cmd` doesn't get called while extension installation.

**Comment by amarkulis** [comment] 2017-08-30 19:58
This isn't a new machine @NimishaS  We have dozens of nodes that have been up for weeks and months.  At some point they get rebooted and the extension tried to update it and it gets stuck in transitioning and throws the error.  

I am able to work around this by using the below lines in powershell 

CD C:\opscode\chef\embedded\bin
./gem install C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005\gems\azure-chef-extension-0.0.1.gem

**Comment by amarkulis** [comment] 2017-08-30 19:59
Maybe the extension could run something similar?

**Comment by NimishaS** [comment] 2017-08-31 06:52
@amarkulis , since this issue is same as https://github.com/chef-partners/azure-chef-extension/issues/226, I am marking this as duplicate. We'll keep https://github.com/chef-partners/azure-chef-extension/issues/226 open as it has logs attached.

**Closed by NimishaS** 2017-08-31 06:52 UTC
