### ISSUE TITLE
Extension uninstallation risks should be reduced

### ISSUE THREAD

**Issue by adamedx** [chef-partners/azure-chef-extension#98] opened 2015-11-30 17:26 UTC
Uninstalling the extension currently uninstalls chef-client, and uninstall happens even when users are not aware, specifically when a new minor version of the extension is released, which is fairly often. This is because Azure interprets minor version updates as a time to update the extension, and "update" is implemented by having the Azure agent disable the extension, uninstall it, and then install it (those "commands" are essentially part of the agent - extension protocol, so the extension simply carries out instructions given by Azure).

In cases where there are race conditions between uninstall and install (often caused by a combination of slow Windows VM's and the generally slow install / uninstall time of chef-client), this can lead to a case where chef-client gets uninstalled and can't be reinstalled during an update triggered by a deployment of the extension (users don't deploy the extension, this happens all the time without their knowledge as Chef updates it to add features). This means that suddenly and without warning, systems can end up in a state where chef-client is uninstalled and the systems are completely unmanageable.

A workaround is to re-add the extension, possibly after a reboot.

We should minimize this possibility with the following plan:

### Phase 1 -- don't uninstall
We should change the extension in the following way:
1. Remove / comment out the line that calls msiexec / dpkg, etc. to uninstall the chef-client -- this makes uninstall a no-op, and has the downside of leaving chef-client behind
2. Verify that if an extension uninstall occurs, the binaries are still there, but the service is disabled.
3. Verify that after an update we see a success and that chef-client service is running successfully.
4. Verify all of the above on Windows, CentOS, Ubuntu

### Phase 2 -- implement delayed uninstall for the update case
To restore the old functionality of uninstall during update, which is a cleaner approach (it gets rid of native gems for instance), make the following changes
1. During unininstall, write some state (e.g. a file) indicating that an uninstall was requested, otherwise do nothing else
2. During install, look for that file -- if it's there, delete it, and then perform an uninstall of chef-client, and then proceed with normal install
3. Verify the update and uninstall cases (uninstall outside the context of update should still not remove chef-client). The failure modes here include failing to update, which is not catastrophic.
Note: we may skip this phase -- we are doing a new installer which is faster and also deletes the chef-client subdirectory, so the uninstall during update may actually be of low value moving forward and not worth this testing / maintenance.

### Phase 3 -- add an "uninstall chef-client" flag
This flag would cause us to uninstall chef-client when requested by Azure -- we'd document that it can cause a risk of loss of service since Azure calls uninstall during extension updates. This would allow users with a strict need to uninstall chef-client and leave behind no trace to do so, while minimizing the risk for mainstream use.

Note that another possibility should also be considered in addition to the above options: we could simply engage in patch updates from now on and not increment the minor version. This would prevent Azure from updating chef-client. However, a downside is that we'd have infrequent testing of what happens with minor version updates, and if we did need to rev the major or minor version, we'd push the risk to that scenario.

**Comment by stuartpreston** [comment] 2015-11-30 17:58
This has saved me a lot of typing! Thanks @adamedx. It strikes me that the majority of these issues are caused by attempting to follow Azure's extension lifecycle - is there some simplification that could be done there if there's a focus on the Azure extension mechanism being a lightweight way to bootstrap a node, but not manage it after that point? After the initial provisioning of the extension, I don't see the value in keeping track of the extension version any more?

**Comment by NimishaS** [comment] 2015-12-08 06:21
Phase 1 is completed here https://github.com/chef-partners/azure-chef-extension/pull/99
and published in extension `1210.12.100.1000`

**Comment by pmarc01** [comment] 2015-12-17 15:25
Hi,

We ran into an issue at a client site where we stood up a large cluster of servers about a month ago. We went to make some updates and saw the majority of the our Azure VM's were missing chef-client entirely. 

I see taht NimishaS had committed the phase 1 change. Any idea how long before that could get incorporated into the Azure marketplace? This is causing us major headaches.

**Comment by NimishaS** [comment] 2016-01-12 13:00
Phase 3 is completed https://github.com/chef-partners/azure-chef-extension/pull/103

**Comment by NimishaS** [comment] 2016-02-29 13:31
This has been resolved in latest extension releases: `1210.12.101.1001` for linux and `1210.12.101.1000` for windows.
Closing this issue. Please re-open in case the issue persists.

**Closed by NimishaS** 2016-02-29 13:31 UTC
