### ISSUE TITLE
Client.rb failure.

### ISSUE THREAD

**Issue by amarkulis** [chef-partners/azure-chef-extension#227] opened 2017-08-28 15:56 UTC
[2017-08-28T15:54:32+00:00] FATAL: Configuration error LoadError: cannot load such file -- chef/azure/chefhandlers/start
_handler
[2017-08-28T15:54:32+00:00] FATAL:   C:/chef/client.rb:41:in `from_string'
[2017-08-28T15:54:32+00:00] FATAL: Aborting due to error in 'C:/chef/client.rb'

Chef is failing on dozens of our nodes from the error above.

This requires me to delete the lines below and then chef goes back to working properly.

require "chef/azure/chefhandlers/start_handler"
require "chef/azure/chefhandlers/report_handler"
require "chef/azure/chefhandlers/exception_handler"

start_handlers << AzureExtension::StartHandler.new("C:/Packages/Plugins/Chef.Bootstrap.WindowsAzure.ChefClient/1210.12.109.1004")
report_handlers << AzureExtension::ReportHandler.new("C:/Packages/Plugins/Chef.Bootstrap.WindowsAzure.ChefClient/1210.12.109.1004")
exception_handlers << AzureExtension::ExceptionHandler.new("C:/Packages/Plugins/Chef.Bootstrap.WindowsAzure.ChefClient/1210.12.109.1004")

**Comment by Vasu1105** [comment] 2017-08-29 11:10
@amarkulis I am unable to reproduce this issue using knife azurerm command. Could you please share more details i.e. what commands you are executing to install chef-extension ?  And share the log files for extension from here C:\WindowsAzure\Logs\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1004

For me its installing latest  chef extension version for windows i.e 1210.12.109.1005

**Comment by amarkulis** [comment] 2017-08-30 15:40
The extension is failing to update which is causing the behavior.  It is stuck in transitioning.  

[logs.zip](https://github.com/chef-partners/azure-chef-extension/files/1261060/logs.zip)

**Comment by NimishaS** [comment] 2017-08-31 07:14
@amarkulis , is this issue different from https://github.com/chef-partners/azure-chef-extension/issues/226?

**Comment by Vasu1105** [comment] 2019-02-05 11:21
Closing this issue due to age.

**Closed by Vasu1105** 2019-02-05 11:21 UTC
