### ISSUE TITLE
Extension on Windows VM timeouts during enable.cmd

### ISSUE THREAD

**Issue by kev-in-shu** [chef-partners/azure-chef-extension#219] opened 2017-07-10 15:09 UTC
On a few servers, I keep getting the following error after the VM restarts in file C:\WindowsAzure\WaAppAgent.log

It results on chef-client not being started on the VM.

> [ERROR] Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1004\enable.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has not exited on time! Killing it...
> [ERROR] Enable command of Chef.Bootstrap.WindowsAzure.ChefClient has exited with Exit code: -2
> [WARN]  Enable failed for plugin (name: Chef.Bootstrap.WindowsAzure.ChefClient, version 1210.12.109.1004) with exception Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1004\enable.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has not exited on time! Killing it..., Code: 1009
> [ERROR] Error while processing plugin Chef.Bootstrap.WindowsAzure.ChefClient version 1210.12.109.1004, state: enabled, error: System.Exception: Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1004\enable.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has not exited on time! Killing it...
>    at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.HandlerStateMachine.InvokeCommand(String command, PluginArtifacts pluginArtifact, String pluginVersion, String pluginFolder, String pluginLogFolder, Int32 processWaitTimeout, PluginEventType startType, PluginEventType endType, CancellationToken ct)
>    at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.HandlerStateMachine.EnableHandler(PluginArtifacts artifact, CancellationToken ct)
>    at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.HandlerStateMachine.StartHandlerStateMachine(PluginArtifacts data, RDConfigHostingEnvironmentSettingsPlugin plugin, CancellationToken ct)
>    at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.PluginInstaller.ProcessPluginArtifacts(PluginArtifacts pluginArtifacts, CancellationToken ct)

**Comment by NimishaS** [comment] 2017-07-10 15:42
@kev-in-shu , are those Windows 2008 servers? Please share the server details.

**Comment by kev-in-shu** [comment] 2017-07-10 20:29
Servers are running Windows 2012r2, with Azure Chef Extension set to install chef 12.

When running enable.cmd myself, the operation does not timeout and the extension initializes itself well.

**Comment by kev-in-shu** [comment] 2017-07-11 16:04
At first I thought it was a problem with my servers being getting a bit old. So yesterday I fired the provisionning of a few more servers as replacement. 

The provisionning failed with the same timeout issue, which was solved the same way by running enable.cmd by hand.

But at next restart, all of these new servers started showing the same issue again: Azure Chef Extension failing at initialization in enable.cmd with a timeout.

This problem has started appearing on our servers since a week now, and it keeps happening on more and more servers. 

Also, let me know if you need more information on the server details.

**Comment by piyushawasthi** [comment] 2017-07-12 08:04
@kev-in-shu - I have tried to reproduce several way this but it's not failing for me. That's very helpful for me if you send me the server details and output of following command for which Azure Chef Extension is failing.

Run this on your powershell and post the output.
` Get-Service -name "chef-client" |select -property name,starttype,status`

**Comment by kev-in-shu** [comment] 2017-07-13 05:38
Installation mode : 
	Chef is installed via AzureRm Templates.

VM specs : 
	D2_v2 or D2_v2_promo running on dev/test subscriptions

OS specs :
	standard image from MicrosoftWindowsServer, WindowsServer, 2012-R2-Datacenter

Get-Service -name chef-client | select -property name, starttype, status

	Name        StartType  Status
	----        ---------  ------
	chef-client Automatic Stopped

Attached files:
	C:\WindowsAzure\Logs\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1004\CommandExecution.log
	C:\WindowsAzure\Logs\WaAppAgent.log



[github-report.zip](https://github.com/chef-partners/azure-chef-extension/files/1144141/github-report.zip)

**Comment by kev-in-shu** [comment] 2017-07-13 06:52
Here is the piece of the ARM template used for chef
```
    {
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "copy": {
          "name": "chefCopy",
          "count": "[parameters('numberOfInstances')]"
      },
      "name": "[concat(variables('vmName'),copyIndex(1),'/chefclient')]",
      "apiVersion": "2015-06-15",
      "location": "[resourceGroup().location]",
      "dependsOn": [
        "[concat('Microsoft.Compute/virtualMachines/', variables('vmName'), copyIndex(1))]",
        "[concat('Microsoft.Compute/virtualMachines/',variables('vmName'), copyIndex(1),'/extensions/joindomain')]"
      ],
      "properties": {
        "publisher": "Chef.Bootstrap.WindowsAzure",
        "type": "ChefClient",
        "typeHandlerVersion": "1210.12",
        "settings": {
          "client_rb": "ssl_verify_mode :verify_none",
          "autoUpdateClient": "true",
          "deleteChefConfig": "false",
          "bootstrap_version": "12",
          "bootstrap_options": {
            "chef_server_url": "[variables('chef_server_url')]",
            "validation_client_name": "[variables('validation_client_name')]",
            "environment": "[parameters('environment')]"
          },
          "runlist": "[parameters('runlist')]"
        },
        "protectedSettings": {
          "validation_key": "[variables('validation_key')]"
        }
      }
    }

```

**Comment by kev-in-shu** [comment] 2017-07-13 06:55
As you can see in the CommandExecution.log file, the failure happens during download of the azure-chef-extension gem, which is probably taking too long and going on timeout.

**Comment by NimishaS** [comment] 2017-07-13 06:58
@kev-in-shu, in `bootstrap_version`, you are passing only 12. It expects a complete version number e.g. `12.0.0`. It would be good to use the latest version of chef-client though, for which u can just remove `bootstrap_version` option from the template.

Can you please try that? I am not 100% sure about this since you said that when you run `enable.cmd` manually, it succeeds.

**Comment by NimishaS** [comment] 2017-07-13 07:14
Also `autoUpdateClient` and `deleteChefConfig` aren't supported anymore, so they can be removed. Although they shouldn't cause the failure.

**Comment by kev-in-shu** [comment] 2017-07-13 08:10
@NimishaS, I am stuck to using version 12 for now, and I still want to get the eventual security updates on chef 12, so that's why I don't want to specify a full version number.

Still, I just ran a test with all 3 options removed (bootstram_version, autoUpdateClient and deleteChefConfig). Provisionning still failed with the same error. In the portal it appears as following:

`{ "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "VMExtensionHandlerNonTransientError", "message": "Handler 'Chef.Bootstrap.WindowsAzure.ChefClient' has reported failure for VM Extension 'chefclient' with terminal error code '1009' and error message: 'Enable failed for plugin (name: Chef.Bootstrap.WindowsAzure.ChefClient, version 1210.12.109.1004) with exception Command C:\\Packages\\Plugins\\Chef.Bootstrap.WindowsAzure.ChefClient\\1210.12.109.1004\\enable.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has not exited on time! Killing it...'" } ] } }`

**Comment by piyushawasthi** [comment] 2017-07-18 09:05
@kev-in-shu - The issue seems to be in Azure. It's not responding with in the time and that's why the extension is failing. Also this issue mostly occurred with multiple VM deployment using ARM templates. We are talking with Azure regarding this issue.

Today, I have created multiple VM with ARM Template 3-4 times and that's work successfully. I have created working ARM template for same: https://github.com/piyushawasthi/multiVM-Windows, Please refer and compare with your template also let me know in case of any concerns.

If you are still facing the issue please send me `CommandExecution` log file at C:\WindowsAzure\Logs\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1004\ and let me know count of VM that you are passing in ARM template.

**Comment by kev-in-shu** [comment] 2017-07-20 11:56
@piyushawasthi - I am also deploying 10 VMs at a time, and the errors happens like 80% of the time.
After the failure, the `CommandExecution` log file looks like the one I provided in a zip in an earlier post in this thread.

I had already noticed there was some randomness (20 to 30% failure rate) in the deployment of the extension a few months ago. But for a few weeks now, the problem has been breaking existing VMs which try and run enable.cmd (not sure why) and fail in the process. 

And in that case the impacted VMs stop running chef-client service at all and don't get any update anymore. At some point the problem impacted around 80% of the existing Virtual machines in one of my subscriptions. After that, I implemented a workaround using Windows Task Scheduler to prevent the extension from breaking itself.

**Comment by kev-in-shu** [comment] 2017-07-20 12:02
Here is a set of CommandExecution log files from a single server for the last 2 weeks.

The failure rate is around 70% for that VM, and like you said it is really looks like some timeout related to network latency.

The first timestamp in the file, right after the `Downloading Chef Client...` trace, occurs at very different times, sometimes a few seconds after the script starts, other times 4 minutes after the beginning of the script, or sometimes it does not even appear at all.

[2017-07-20 Report2.zip](https://github.com/chef-partners/azure-chef-extension/files/1162170/2017-07-20.Report2.zip)

**Comment by piyushawasthi** [comment] 2017-07-31 09:40
@kev-in-shu - Issue fixed in these PR: https://github.com/chef/mixlib-install/pull/226, https://github.com/chef/mixlib-install/pull/228

**Comment by stuartpreston** [comment] 2018-10-05 22:44
Closing this issue due to age.  If you continue to experience issues here, please open a new issue.  Thanks.

**Closed by stuartpreston** 2018-10-05 22:44 UTC
