### ISSUE TITLE
Chef extension update creating nested chef_backup folders

### ISSUE THREAD

**Issue by amarkulis** [chef-partners/azure-chef-extension#198] opened 2017-03-24 02:41 UTC
It appears even though we have autoUpgradeMinorVersion set to false we are automatically receiving extension updates.  The current logic in chef-update.ps1 is   

"$backupLocation = Get-TempBackupDir
    $calledFromUpdate = $True
    # Save chef configuration.
    Copy-Item $bootstrapDirectory $backupLocation -recurse
    Write-Host "[$(Get-Date)] Configuration saved to $backupLocation""

which is causing a chef_backup folder to be nested within the  chef_backup folder repeatedly.  We have seen multiple servers run out of space from this issue.

**Comment by michael-tam** [comment] 2017-03-24 02:51
We are experiencing this problem as well!  Is there a way to prevent new versions of the azure-chef-extension from re-installing the chef-client?

**Comment by NimishaS** [comment] 2017-03-25 03:58
@michael-tam , there's a work around to keep the chef-client version constant. There is an option `bootstrap_version` where the version of `chef-client` can be mentioned. If this option is sent while the first installation of azure-chef-extension, the version of `chef-client` remains same during the updates too. Otherwise, the latest version of `chef-client` is downloaded by default with each update.

Please follow these steps:
1. Add `bootstrap_version` option in `C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.<latest_extension_version>\RuntimeSettings\n.settings` file (here `n` is the latest settings file in your system). Refer this gist: https://gist.github.com/NimishaS/140557eded63c4dae0fd44c486e1d33d
*Note*: I have added new-lines in the gist to make it readable.
2. Uninstall `chef-client` manually.
3. Delete the registered node from chef-server.
4. Delete `C:\chef`.
5. Run `enable` command `C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.<latest_extension_version>\enable.cmd` manually on the server.

**Comment by NimishaS** [comment] 2017-03-25 04:07
@amarkulis , there is a bug in Azure extension design that it's agent(Waagent) calls the update even after setting `autoUpgradeMinorVersion` false. This needs to be fixed by Azure.
Can you please share the screenshot of `chef_backup` folder? The problem is that when we try to reproduce this issue by manually running update, it runs only when there's a change in the major version of `azure-chef-extension`. We tried updating the extension version once. That created a single `chef_backup` folder. In your case there must have been multiple updates. It would be helpful if you can share the screenshot of multiple backups.

**Comment by michael-tam** [comment] 2017-03-25 05:11
@nimishas  We are using the bootstrap version, I was wondering if there was a way to prevent Azure Extension from updating.  It sounds like autoUpgradeMinorVersion should prevent that.  

The reason there is multiple backup folders is because it creates chef_backup inside c:/chef.  The next time it backs up, it backs up c:/chef which contains chef_backup.

**Comment by NimishaS** [comment] 2017-03-27 06:28
@michael-tam we are working on fixing the multiple backup issue. Regarding `autoUpgradeMinorVersion`, please refer my comment: https://github.com/chef-partners/azure-chef-extension/issues/198#issuecomment-289187199

**Comment by amarkulis** [comment] 2017-03-27 16:18
![image](https://cloud.githubusercontent.com/assets/26640711/24366567/1d8675f2-12df-11e7-8daf-f00e602291d0.png)
@NimishaS

**Comment by NimishaS** [comment] 2017-03-28 10:44
@amarkulis , @michael-tam, Fix for this issue is available in the latest windows extension `1210.12.109.1002`.

For the existing VMs with the extension, it's required to manually delete the `chef_backup` folder first.

**Comment by NimishaS** [comment] 2017-03-29 06:01
@amarkulis , @michael-tam , can you please verify if the issue of nested backups is resolved for you. Please close this issue if it's resolved.

**Comment by NimishaS** [comment] 2017-03-31 15:36
Closing this issue. @amarkulis , @michael-tam please contact in case you still face this issue.

**Closed by NimishaS** 2017-03-31 15:36 UTC
