### ISSUE TITLE
Receiving error when deploying Chef Client through ARM Templates.

### ISSUE THREAD

**Issue by aw230012** [chef-partners/azure-chef-extension#220] opened 2017-07-13 17:14 UTC
Hello everyone,

I'm seeing a similar behavior to others, although my error message is different.  When trying to deploy the WindowsAzure.ChefClient on a MicrosoftSQLServer instance with SQL2016SP1-WS2016 Enterprise SKU we consistently receive the following error:

> Enable failed for plugin (name: 
Chef.Bootstrap.WindowsAzure.ChefClient, version 1210.12.109.1004) with exception Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1004\enable.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has exited with Exit code: 1'

Below is the resource template:

>     {
>       "type": "Microsoft.Compute/virtualMachines/extensions",
>       "name": "[concat(parameters('vmName'), '/ChefExtension')]",
>       "apiVersion": "2016-04-30-preview",
>       "location": "[resourceGroup().location]",
>       "properties": {
>         "publisher": "Chef.Bootstrap.WindowsAzure",
>         "type": "[parameters('options').chefType]",
>         "typeHandlerVersion": "1210.12",
>         "settings": {
>           "bootstrap_options": {
>             "chef_node_name": "[parameters('vmName')]",
>             "chef_server_url": "[parameters('options').chefServerUrl]",
>             "validation_client_name": "[parameters('options').chefValidationClientName]",
>             "node_ssl_verify_mode": "none",
>             "environment": "[parameters('options').chefEnvironment]"
>           },
>           "runlist": "[parameters('options').runlist]",
>           "validation_key_format": "base64encoded"
>         },
>         "protectedSettings": {
>           "validation_key": "[parameters('options').chefValidationKey]"
>         }
>       }
>     }

The Chef type is set to ChefClient and we are trying to create runlist with two recipes.  The other details are sensitive and cannot be shared.

Has anyone else seen this issue?  Am I missing something in the setup?

Thanks!

**Comment by kev-in-shu** [comment] 2017-07-13 17:49
Hi @aw230012 , 
I've been seing the same kind of error almost systematically for a week now.

In my case, looking at the following log files make it appear the extension is getting a timeout:
```
C:\WindowsAzure\Logs\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1004\CommandExecution.log
C:\WindowsAzure\Logs\WaAppAgent.log
```

I tried to run the enable.cmd script by hand, and it does initialize correctly, albeit very slowly.

On the other hand, on server restart, the extension often tries to reinstall itself, then gets the timeout again, in which case I am stuck again with a node that does not connect to chef server.

**Comment by aw230012** [comment] 2017-07-14 13:31
It's very intermittent, which I've seen others report as well.  Yesterday it failed 2 out of 3 times, same error.  Then worked on the 3rd attempt.  Unfortunately, we're deploying very large SQL Server instances so it's such a time sink to try 3 times to have it behave as expected.  There is also no detail for me to help figure-out the problem.  What's exit code 1 mean?  Tell me the real issue if it's a timeout, a connection issue, something.

**Comment by piyushawasthi** [comment] 2017-07-17 15:07
@aw230012 - Issue not reproduced with ARM template for VM `SQL Server 2016 SP1 Enterprise on windows server 2016`. 

I have created working ARM template for same: https://github.com/piyushawasthi/sql2016-win2016-Enterprise, Please refer and compare with your template and let me know in case of any concerns.

**Comment by aw230012** [comment] 2017-07-17 15:56
Thanks @piyushawasthi, I will double-check our template with your's and see if we're missing something.  The error I reported about does not happen all the time.  If I do five deploys, we see it 2 or 3 times.  It's very strange behavior.

**Comment by amarkulis** [comment] 2017-07-20 21:26
We are seeing the same behavior on hundreds of machines.  It has brought us to start investigating moving away from this extension. Here are the errors we see in the log areas mentioned above. 
--------------WaAppAgent---------------------------------------------
[00000014] [07/13/2017 22:48:25.02] [WARN]  Enable failed for plugin (name: Chef.Bootstrap.WindowsAzure.ChefClient, version 1210.12.109.1004) with exception Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1004\enable.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has exited with Exit code: 1, Code: 1009
[00000014] [07/13/2017 22:48:25.03] [ERROR] Error while processing plugin Chef.Bootstrap.WindowsAzure.ChefClient version 1210.12.109.1004, state: enabled, error: System.Exception: Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1004\enable.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has exited with Exit code: 1
   at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.HandlerStateMachine.InvokeCommand(String command, PluginArtifacts pluginArtifact, String pluginVersion, String pluginFolder, String pluginLogFolder, Int32 processWaitTimeout, PluginEventType startType, PluginEventType endType, CancellationToken ct)
   at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.HandlerStateMachine.EnableHandler(PluginArtifacts artifact, CancellationToken ct)
   at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.HandlerStateMachine.StartHandlerStateMachine(PluginArtifacts data, RDConfigHostingEnvironmentSettingsPlugin plugin, CancellationToken ct)
   at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.PluginInstaller.ProcessPluginArtifacts(PluginArtifacts pluginArtifacts, CancellationToken ct)
[00000015] [07/13/2017 23:03:22.01] [HEART] WindowsAzureGuestAgent Heartbeat.

---------------------CommandExecution-------------------------------
[2017-07-07T19:08:39+00:00] ERROR: Error enabling chef-client service (Expected process to exit with [0], but received '1058'
---- Begin output of sc.exe start chef-client  -c C:/chef\client.rb -L C:\WindowsAzure\Logs\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1004\chef-client.log  ----
STDOUT: [SC] StartService FAILED 1058:
The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.
STDERR: 
---- End output of sc.exe start chef-client  -c C:/chef\client.rb -L C:\WindowsAzure\Logs\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1004\chef-client.log  ----
Ran sc.exe start chef-client  -c C:/chef\client.rb -L C:\WindowsAzure\Logs\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1004\chef-client.log  returned 1058)
Logging status message: chef-service enable failed - ["Error enabling chef-client service - Expected process to exit with [0], but received '1058'\n---- Begin output of sc.exe start chef-client  -c C:/chef\\client.rb -L C:\\WindowsAzure\\Logs\\Plugins\\Chef.Bootstrap.WindowsAzure.ChefClient\\1210.12.109.1004\\chef-client.log  ----\nSTDOUT: [SC] StartService FAILED 1058:\r\n\r\nThe service cannot be started, either because it is disabled or because it has no enabled devices associated with it.\nSTDERR: \n---- End output of sc.exe start chef-client  -c C:/chef\\client.rb -L C:\\WindowsAzure\\Logs\\Plugins\\Chef.Bootstrap.WindowsAzure.ChefClient\\1210.12.109.1004\\chef-client.log  ----\nRan sc.exe start chef-client  -c C:/chef\\client.rb -L C:\\WindowsAzure\\Logs\\Plugins\\Chef.Bootstrap.WindowsAzure.ChefClient\\1210.12.109.1004\\chef-client.log  returned 1058 - Check log file for details", "error"]


Execution Error:

######
Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1004\enable.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has exited with Exit code: 1

**Comment by amarkulis** [comment] 2017-07-20 21:28
It looks like using the command "sc.exe start chef-client -c C:/chef\client.rb" is the culprit.

**Comment by piyushawasthi** [comment] 2017-07-21 09:08
@amarkulis - Looks like your `chef-client` service startup type is `disabled`. I have already fixed that issue in PR: https://github.com/chef-partners/azure-chef-extension/pull/217

You can verify `chef-client` service start-up type by executing below command on PowerShell.
`Get-Service -name chef-client | select -property name, starttype, status`

**Workaround is run following script in your PowerShell.**
```
1: Set-Service -Name 'chef-client' -StartupType automatic
2: sc.exe start chef-client
```
Then verify the chef-client service status by PowerShell command.
`Get-Service -name chef-client | select -property name, starttype, status`

**Comment by amarkulis** [comment] 2017-07-21 13:49
The issue was that we weren't specifying daemon I think.

**Comment by NimishaS** [comment] 2017-07-24 05:44
@amarkulis , if daemon isn't specified then the default value of daemon is `service`. So chef-client service should get created and enabled.

**Comment by amarkulis** [comment] 2017-07-24 14:03
@NimishaS Per Chef's recommendation we use the scheduled task and disable the windows service.  I believe that is what was causing the problem since the extension was trying to start the service we disable.

**Comment by amarkulis** [comment] 2017-07-25 15:04
Is there a way to specify the user the scheduled task will run under?

**Comment by roberto-mardeni** [comment] 2017-07-26 15:49
I have been having the same issue and it appears to be mitigated when changing the VM size to something like Standard_D2_V2, which is really a problem if you want to deploy to smaller VMs.

**Comment by piyushawasthi** [comment] 2017-07-31 09:38
@amarkulis - Currently there is no way to run scheduled task under a specific user.

**Comment by piyushawasthi** [comment] 2017-07-31 13:12
@roberto-mardeni - Please use VM size `Standard_DS2_v2` instead of `Standard_D2_v2`.

Also I have created working ARM template for same: https://github.com/piyushawasthi/ARM-Template/tree/master/win12-D2-V2, Please refer and compare with your template and let me know in case of any concerns.

**Comment by piyushawasthi** [comment] 2017-08-04 13:57
@roberto-mardeni - Please confirm if above comment work for you.

**Comment by piyushawasthi** [comment] 2017-08-04 13:57
@roberto-mardeni - Please confirm if above comment work for you.

**Comment by roberto-mardeni** [comment] 2017-08-04 16:39
Sorry for the late response, it definitely did, however this makes it harder to justify using the extension if somebody needs to use this extension in VMs of smaller size due to the likelihood of failure.

**Comment by piyushawasthi** [comment] 2017-08-07 12:07
@roberto-mardeni - Please share your region for which you want vmSize `Standard_D2_V2`.

**Comment by NimishaS** [comment] 2017-08-07 12:50
@amarkulis , since the error you are getting `StartService FAILED 1058` is different from the error mentioned in this issue, can you please create a new issue and share the steps to reproduce the issue?
 Please share your ARM template too, including the SKU details.
We have recently published windows extension `1210.12.109.1005`  to fix the service related issue, but we would like to test it with your scenario.

**Comment by amarkulis** [comment] 2017-08-07 13:57
@NimishaS I think our issue is due to the fact that we did not specify a daemon and the first thing our chef recipes do is disable the chef service and set up scheduled task.

**Comment by NimishaS** [comment] 2017-08-08 05:55
Since there are multiple conversations for different contexts going on here, I would still suggest to create a separate issues.

@amarkulis , @roberto-mardeni, your issues are different. If there will be separate issues for different problems, it will be easier for people in future also to search if they face similar issues. Right now I can see discussion for 3 different issues in the same thread.

**Comment by piyushawasthi** [comment] 2017-08-08 07:40
@amarkulis - There is no need to execute any chef recipes to setup scheduled task or disable chef service. In ARM template you need to pass `task` to daemon option. `task` will configure chef-client as a scheduled task.

Please check the description of daemon option here: https://github.com/chef-partners/azure-chef-extension/blob/master/README.md#azure-chef-extension-usage

**Comment by amarkulis** [comment] 2017-08-23 03:23
@piyushawasthi I wish that were true but we require that the scheduled task run under a specific user.

**Comment by NimishaS** [comment] 2017-08-23 06:48
@amarkulis , in that case you can pass `daemon=none` and then use your recipe to create the scheduled task. 
When you pass `daemon=none`, it doesn't any create chef-service or chef scheduled task. So you won't require the recipe to disable service too.

**Comment by Vasu1105** [comment] 2019-02-05 10:53
Closing this issue due to age.

**Closed by Vasu1105** 2019-02-05 10:53 UTC
