### ISSUE TITLE
High CPU utilizaton on Windows 2019

### ISSUE THREAD

**Issue by sgkoutscloudreach** [chef-partners/azure-chef-extension#329] opened 2020-09-16 11:00 UTC
Hi,

I would like to inform you about the issue when using the extension with Windows 2019.

We are observing intermittent prolonged high CPU utilization which is showing up in the event logs as WMI errors. When inspecting the logs we found that the following line is the culprit:

`powershell -nologo -noprofile -executionpolicy unrestricted Import-Module C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1002\bin\chef-install.psm1;Install-ChefClient] [16400.13644] [ExecQuery: select * from Win32_Product]`

After removing the extension but leaving Chef installed on the machine, there are no errors

**Comment by ayushbhatt29** [comment] 2020-10-07 13:22
Hello @sgkoutscloudreach, can you please try to upgrade your azure-chef-extension version as the one you are using is too old and we are not able to reproduce the same on latest azure-chef-extension version.

**Comment by sgkoutscloudreach** [comment] 2020-10-07 13:24
Hi @ayushbhatt29. I will try and get back to you.

Thanks

**Comment by ayushbhatt29** [comment] 2020-10-07 13:32
@sgkoutscloudreach sure, Thank you.

**Comment by ayushbhatt29** [comment] 2020-11-02 13:11
@sgkoutscloudreach any updates ?

**Comment by sgkoutscloudreach** [comment] 2020-11-03 09:28
Hi @ayushbhatt29. I didn't have a chance to test the servers that had issues but I can confirm that other Windows 2019 servers do not have the same issue, so it appears to be related to the version of the extension

**Comment by Vasu1105** [comment] 2020-11-03 09:52
@sgkoutscloudreach  so can we close this issue ?

**Comment by sgkoutscloudreach** [comment] 2020-11-03 09:54
@Vasu1105 yes, please. If it reoccurs again I will be getting in touch again.

Thank you.

**Comment by Vasu1105** [comment] 2020-11-03 10:00
Thank you @sgkoutscloudreach.

**Closed by Vasu1105** 2020-11-03 10:00 UTC
Labels: Type: Bug
