### ISSUE TITLE
No such file or directory @ rb_sysopen - C:/chef\\client.rb

### ISSUE THREAD

**Issue by leovms** [chef-partners/azure-chef-extension#240] opened 2017-11-30 13:21 UTC
Running the *Windows Chef Extension* on *Windows 10 Pro, Version 1709* via Azure Portal results in the following exception:

```
chef-service enable failed - ["Error enabling chef-client service - No such file or directory @ rb_sysopen - C:/chef\\client.rb - Check log file for details", "error"]
```

**Comment by dheerajd-msys** [comment] 2017-12-04 13:22
@leovms , Thanks for pointing this out. I have reproduced this issue from my end and we will be fixing it soon.

**Comment by leovms** [comment] 2017-12-06 13:51
@dheerajd-msys, thank you for the update. Because we have a bug open in our backlog related to this, could you please update when the fix is out, so we can validate and close the corresponding bug on our side?

**Comment by leovms** [comment] 2017-12-15 14:03
@dheerajd-msys, any update on this issue? Thanks.

**Comment by dheerajd-msys** [comment] 2017-12-21 06:01
@leovms We are still trying to figure out the root cause for this issue. We will update you once we come up with the fix. Thanks.

**Comment by dheerajd-msys** [comment] 2019-02-12 05:24
@leovms Are you still facing this issue? Please let us know if there is anything.

**Comment by dheerajd-msys** [comment] 2019-04-25 06:04
@leovms  As recent versions of Windows 10 e.g Windows 10 Pro 1809 doesn't exhibit this issue so could you please try to use latest versions.

Closing this issue for now. 
Thanks.

**Closed by dheerajd-msys** 2019-04-25 06:04 UTC
