### ISSUE TITLE
Azure Server Create fail with "wagent provisioning" state not reached after 5 minutes

### ISSUE THREAD

**Issue by ghost** [chef-partners/azure-chef-extension#137] opened 2016-05-20 10:07 UTC
We are currently trying out the Knife Azure plugin, and using the ASM mode Server Create command.
It's constantly generating an error similar to the following:

```
..................ERROR: Resource extension state 'wagent provisioning' not reached after 5 minutes. chef-service enabled
ERROR: Failed to create the server -- exception being rescued: Verify connectivity to Azure and subscription resource limit compliance (e.g. maximum CPU core limits) and try again.
WARNING: Cleaning up resources...
```

Here are some relevant details:
1. we are using the azure-chef extension version 1210.12.102.1000, set via following
   knife[:azure_chef_extension_version] = '1210.12'
2. We are trying to provision a "Large" vm with "Windows 2012 R2"
3. We are using a hosted chef account for provisioning a simple webserver cookbook
4. After the Azure Knife exception (described above), the VM is still in Running state, and accessible via RDP.
5. On further investigation it appears that the Chef Extension is installed on the VM and logs are available under C:\WindowsAzure\Logs\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient
6. C:\chef directory also appears to have all the files for the cookbooks downloaded and available.

I have also attached the log from azure chef extension plugin. Any immediate help would be well appreciated.

[chef-client.log.txt](https://github.com/chef-partners/azure-chef-extension/files/274353/chef-client.log.txt)
[CommandExecution.log.txt](https://github.com/chef-partners/azure-chef-extension/files/274354/CommandExecution.log.txt)
[CommandExecution_0.log.txt](https://github.com/chef-partners/azure-chef-extension/files/274355/CommandExecution_0.log.txt)

**Comment by NimishaS** [comment] 2016-05-20 10:38
@jayb8621 , does it mean that you `knife azure server create` is failing but extension is getting installed successfully?
The log files attached here show successful execution.

**Comment by jayb8621** [comment] 2016-05-20 10:46
Yes. The knife azure "server create" command fails with the exception as described in the issue. I appreciate your quick reponse re this. Looking forward to a quick resolution.


Sent via the Samsung Galaxy S® 4 mini ™, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Nimisha Sharad <notifications@github.com> </div><div>Date:05/20/2016  6:38 AM  (GMT-05:00) </div><div>To: chef-partners/azure-chef-extension <azure-chef-extension@noreply.github.com> </div><div>Cc: SujitBasu <sujit_basu@hotmail.com>, Mention <mention@noreply.github.com> </div><div>Subject: Re: [chef-partners/azure-chef-extension] Azure Server Create fail with "wagent provisioning" state not reached after 5 minutes (#137) </div><div>
</div>
@jayb8621 , does it mean that you `knife azure server create` is failing but extension is getting installed successfully?
The log files attached here show successful execution.

---

**Comment by jayb8621** [comment] 2016-05-20 12:24
Windows image we are using is following:
a699494373c04fc0bc8f2bb1389d6106__Windows-Server-2012-Datacenter-20160329-en.us-127GB.vhd

**Comment by jayb8621** [comment] 2016-05-23 21:49
@NimishaS, any feedback on why we are getting this error? I provided the Azure Image name above. Any  particular image that works well?

**Comment by Vasu1105** [comment] 2016-05-24 06:07
@jayb8621 I am unable to reproduce the issue using the same image that you mentioned above. Could you please also attach the wagent log ?

**Comment by jayb8621** [comment] 2016-05-24 11:10
@Vasu1105 could you kindly provide the location of the logs on the windows VM, you have requested?

**Comment by Vasu1105** [comment] 2016-05-24 11:30
@jayb8621 It's in C:\WindowsAzure\Logs\wagent.log

**Comment by jayb8621** [comment] 2016-05-25 02:43
Appreciate your response.
I could not find any wagent.log under the dir you mentioned. Re-ran the "server create" command, which generated the same error described above. This time, no wagent.log found. I have uploaded the whole c:\WindowsAzure\Logs directory to "onedrive". You can download using this link...https://onedrive.live.com/redir?resid=FD2339DBF855BAB6!880&authkey=!AApvEXlJag_eXpE&ithint=file%2czip

**Comment by Vasu1105** [comment] 2016-05-25 04:39
@jayb8621  My bad its WaAppAgent file in the logs directory. I looked into your log directory WaAppAgent log is not having any error. So as you said everything looks good on the VM logs. Sorry, I need few more details from you i.e. the knife azure command that you are trying and the knife-azure extended logs with -VV option.

**Comment by Vasu1105** [comment] 2016-05-25 16:01
@jayb8621  One more thing can you verify that does your node got registered on the chef server ?

**Comment by NimishaS** [comment] 2017-04-06 06:59
@ghost, can you please try with the latest extension and verify if you still face this issue. We haven't faced timeout issue on `Windows 2012 R2`. 
For `Windows 2008` , we get this error intermittently. Please use the latest images to avoid this issue.

**Comment by dheerajd-msys** [comment] 2018-06-22 13:16
@ghost, Any update on this issue?

**Comment by stuartpreston** [comment] 2018-10-05 22:47
Closing this issue due to age.  @ghost if you continue to experience issues here, please open a new issue.  Thanks.

**Closed by stuartpreston** 2018-10-05 22:47 UTC
